### ISSUE TITLE
The mobile menu navigation has display issue

### ISSUE THREAD

**Issue by arvi** [webiny/webiny-js#1173]
Css issue on default webiny header navigation on mobile

## This is:
- Bug

## Specifications

  - version: 4.6.0
  - OS: Mac OS
  - Browser: Chrome & Brave (Mobile Phone)

## Expected Behavior
Mobile menu display is block or list-item: https://ibb.co/gTb4zyN

## Actual Behavior
Mobile menu display is flex: https://ibb.co/X70br0F

## Steps to Reproduce the Problem

1. View the website menu in mobile view

## Detailed Description
It seems there is no specific css for mobile menu.

## Possible Solution
I added this on my project to fix issue. 

```css
@include mobile{
  .webiny-pb-section-header {
    &__navigation {
      ul{
        display: list-item !important;
        list-style-type: none;
      }
    }
  }
}
```
