### ISSUE TITLE
Form submissions doesn't have scroll functionality

### ISSUE THREAD

**Issue by arvi** [webiny/webiny-js#1189]
## This is:
- Bug

## Specifications

  - version: Webiny 4.8.0
  - OS: Mac OS
  - Browser: Chrome

## Expected Behavior
I should be able to scroll the form submissions list

## Actual Behavior
Depending on screen size, you can only see the latest submissions. In a 13inch laptop, I can only see 2 out of 20 submissions

## Steps to Reproduce the Problem

1. Create a form
2. Submit entry multiple times
3. Go to Forms and try to scroll through submissions.

## Possible Solution

This is what I applied to fix the issue for the meantime.
```scss
.mdc-layout-grid .mdc-list {
  overflow-y: scroll;
  overflow-x: hidden;
  height: calc(100vh - 32px);
  position: relative;
}
```
