### ISSUE TITLE
Buttons have unnecessary top margin

### ISSUE THREAD

**Issue by arvi** [webiny/webiny-js#1190]
## This is:

- Bug

## Specifications

  - version: 4.8.0
  - OS: Mac OS
  - Browser: Chrome

## Expected Behavior

When you create an `H1, H2, H3, H4, H5, H6` button, it should have default margin

## Actual Behavior

There is unnecessary margins for buttons that are not `p`

## Steps to Reproduce the Problem

1. Create a button that is either `H1, H2, H3, H4, H5, H6` 
2. Check the rendered output and you'll notice the margin top

## Possible Solution

```css
.webiny-pb-page-element-button .webiny-pb-typography-h1,
.webiny-pb-page-element-button .webiny-pb-typography-h2,
.webiny-pb-page-element-button .webiny-pb-typography-h3,
.webiny-pb-page-element-button .webiny-pb-typography-h4,
.webiny-pb-page-element-button .webiny-pb-typography-h5,
.webiny-pb-page-element-button .webiny-pb-typography-h6 {
  margin-top: 0;
}
```
