### ISSUE TITLE
Create a logging system to improve debugging

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#625]
# The problem
Currently we're facing a very difficult and slow debugging process in the cloud. You get a blank screen - now what? Even better - `internal server error`. So helpful 🤦‍♂. So the process looks like this: you open your lambdas and begin digging through tons of CloudWatch streams, which are very often concurrent, so a single lambda can have 5-10 streams.

# Potential solution
Our `serverless-apollo-service` can easily support handler wrapping via plugins (I've tested it in my fork, works nicely). This allows us to intercept every event that comes into the lambda, log it, then execute the handler, log the response, and catch errors to log them as well. Logging could be performed via websockets (most effective from both time/performance and cost perspective).

The process:
- create a new component which would deploy a WebSocket API Gateway with a Log Dispatcher lambda
- create a logger plugin which will wrap the Apollo handler in each service
- whenever a service lambda receives a request, it connects to the Log Dispatcher and keeps the connection open
- whenever there is something to log, an event, console.log, error - we use that connection to push messages to the Log Dispatcher
- the Log Dispatcher in turn can process the message using any number of plugins, and either store the messages to DB or send them to other websocket clients

# Proof of concept
To test this concept it is enough to only implement the websocket plugin so I can connect to my log dispatcher from my local machine. This will allow me to monitor any project by simply connecting to its Log Dispatcher via WS. At this point I don't care so much about storing to DB, I just want to get a decent flow of logs to my local machine to easier search through logs.

Once this POC is working, either we or the community can begin developing better UI to analyze logs. For example, you can easily create a VSCode plugin which is running a simple React app, and create a few simple filters to analyze logs. Sky is the limit here.

**Comment by SvenAlHamad** [comment]
Why not use a ready-made solution like Lumigo, iopipe or something similar and write a Webiny integration for that?

**Comment by Pavel910** [comment]
That's the cool thing in the long run, because all this is implemented as a plugin on top of your service. So if you want Lumigo, go ahead, create a plugin which will connect your handler to Lumigo (or any other tool). 

But those tools are not free, and we can't expect people to go spend money on observability tools as as soon as they want to try and tincker with Webiny. 

So my proposal is to create an initial working logger, pretty simple, but pluginable, so later people can expand on that. And we will have some basic tools to debug things without paying right away. It would also help us, as the core team, to debug stuff for people without asking them to give us access to their AWS accounts. All we'd need is a WS connection URL.

**Comment by SvenAlHamad** [comment]
It makes perfect sense.

In terms of the debug tool, how do we want to control when debug is active or not. I assume for production sites, it should be turned off by default. Also, you might not want to have this on/off toggle site-wide, but that a developer can activate the debug only for himself for a particular environment.

**Comment by Pavel910** [comment]
So logging is only happening when you have this "handler wrapper" plugin. Each service must have this plugin defined (so technically you can only log 1 particular service, not everything, if you like). 

Each plugin of course can take an `options` object, which defines whether it's logging or not, like `enabled: true/false`. This can then we tied to `env` variables: `enabled: ${vars.logging.enabled}`. When the plugin runs, it it is not enabled, it will simply return the original `handler`, and not even attach itself to console.log, etc. 

Here is an example configuration, for example `i18n` service:

```yml
i18n:
  component: "@webiny/serverless-apollo-service"
  inputs:
    name: I18N
    region: ${vars.region}
    memory: 512
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
      - factory: "@webiny/api-plugin-lambda-logger"
        options:
          url: ${logDispatcher.api.url}
          enabled: ${vars.logger.enabled}
      - factory: "@webiny/api-plugin-commodo-mongodb"
        options: ${vars.commodo}
      - factory: "@webiny/api-security/plugins/service"
        options: ${vars.security}
      - "@webiny/api-i18n/plugins"
```

Notice the second plugin called `"@webiny/api-plugin-lambda-logger`. So you can control everything easily via `env` variables, meaning it's per-environment.

**Comment by SvenAlHamad** [comment]
Cool, it makes sense. So the main focus of this plugin is to be used as part of your development process? Meaning it won't store any logs aside and wait for the developer to review them. The logs will be streamed back to the developer's machine as he's testing/developing the service.

**Comment by Pavel910** [comment]
You can have plugins for different purposes. The initial version I envisioned is a simple `streaming log`, so you have to connect to WS and log the messages yourself. Here is an example of how I plan to implement the `Log Dispatcher` component:

```yml
logDispatcher:
  component: "@webiny/serverless-logger"
  input:
    plugins:
      - factory: "@webiny/serverless-logger-websocket"
      - factory: "@webiny/serverless-logger-dynamodb"
```

So what this does is it deploys a Websocket API Gateway which is always there, waiting for lambdas to push messages using the `@webiny/api-plugin-lambda-logger` (a wrapper which will push messages to the Log Dispatcher). When the `Dispatcher` receives a message, it can than use 1 or more plugins to store them to DB or forward to another URL, or send to websocket clients, whatever the plugin does. This way we can have multiple logging destinations.

For this initial version I only want to implement the websocket part, so I can connect to the `stream` and log messages in my terminal. Simple process, just to setup the basic structure.

**Comment by SvenAlHamad** [comment]
Looks great, and more importantly, it's pluggable and has options for future extensions.

**Comment by Pavel910** [comment]
This is a piece of `serverless.yml` that showcases the configuration of a logger:

```yml
vars:
  region: ${env.AWS_REGION}

# HTTP logger is a REST API which uses plugins to process the received payloads.
logger:
  component: "@webiny/serverless-http-logger"
  inputs:
    region: ${vars.region}
    plugins: 
      # This plugin will connect to a WS API and send the payloads as socket messages
      - factory: "@webiny/serverless-logger-websocket/reporter"
        options:
          socket: ${wsLogger.api.url}

# This component is used if you want to stream logs via websocket to your client.
# It deploys an WS API and broadcasts all messages to the connected clients.
wsLogger:
  component: "@webiny/serverless-logger-websocket"

i18n:
  component: "@webiny/serverless-apollo-service"
  inputs:
    name: I18N
    region: ${vars.region}
    memory: 512
    plugins:
      # This plugin will wrap the Apollo Handler and POST logs to the `logger` via HTTP
      - factory: "@webiny/api-plugin-http-function-tracer"
        options:
          target: ${logger.api.url}
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
```

To recap:
1) the `logger` component creates a simple REST API to serve as a hub for all log messages, nothing more.
2) in any apollo-service (here I used `i18n`), you add a plugin `@webiny/api-plugin-http-function-tracer` which wraps the Apollo handler and sends log payloads to the `logger` via simple HTTP POST requests (it will intercept all `console.log`s, lambda events, errors, timings, etc).

Now we need to somehow consume those logs: in our case we want to be able to consume logs via websocket, so first we need a Websocket API, that's what `wsLogger` component does - it creates a Websocket API. And the last thing is something that will push those log messages from the HTTP Hub to the Websocket API. That's what `@webiny/serverless-logger-websocket/reporter` does.

@SvenAlHamad  @doitadrian  Let me know if you have questions, suggestions, etc.
