### ISSUE TITLE
I cannot seem to upload some images

### ISSUE THREAD

**Issue by mectors** [webiny/webiny-js#638]
Uploading some images gives an error while uploading another image does not

## This is:

- Bug

## Specifications

  - version: 2.4.1
  - OS: Mac and AWS
  - Browser: Chrome

## Expected Behavior

All the images that are visible in the page builder image selector should be able to be added to the image element

## Actual Behavior

Some work fine but others do not appear. When adding them a broken image item appears and when opening the image, e.g. https://dut1alnks85jp.cloudfront.net/files/8k3ubshlo-myclientsleft.png?width=2500, then {"message": "Internal server error"} is shown. Unclear why. Unclear how and why certain images work and others do not.

**Comment by Pavel910** [comment]
@mectors is that a file of your own that you uploaded? If so, could you please send it over to us? We'd like to test using the exact same file. Either drop me an email (see my profile for the address) or join us on https://gitter.im/Webiny/webiny-js and send via private message. It will help a lot to pinpoint the problem.

Thanks a lot!

**Comment by doitadrian** [comment]
Hi @mectors,

I tried opening your image, and yeah, I cannot load it.

I noticed the `width=2500`, so I simply tried `width=1000`, and that worked.

https://dut1alnks85jp.cloudfront.net/files/8k3ubshlo-myclientsleft.png?width=1000

I will check how the dimensions of the image can cause issues.

**Comment by doitadrian** [comment]
I managed to reproduce the issue with your image.

Will fix this!

**Comment by mectors** [comment]
thanks

**Comment by doitadrian** [comment]
This has been fixed @mectors. 

Basically, the function that was doing image resizing wasn't equipped with enough system resources.

I released the fix for this, so new users won't experience on the same issue. For your existing Webiny setup, the easiest way to fix this would be to go to the `api/serverless.yml`, search for `imageTransformer` key, located in `files` component, and change the memory to 1600, and timeout to 30.

Once changed, the `files` component might look like the following:

```yml
files:
  component: "@webiny/serverless-files/dist"
  inputs:
    region: ${vars.region}
    bucket: ${vars.bucket}
    functions:
      apolloService:
        memory: 512
        timeout: 10
        uploadMinFileSize: 0 # 0 MB
        uploadMaxFileSize: 26214400 # 25 MB
        webpackConfig: ./webpack.config.js
        plugins:
          - factory: "@webiny/api-plugin-create-apollo-handler"
            options: ${vars.apollo}
          - factory: "@webiny/api-plugin-commodo-mongodb"
            options: ${vars.commodo}
          - factory: "@webiny/api-security/plugins/service"
            options: ${vars.security}
          - "@webiny/api-files/plugins"
          - "@webiny/api-plugin-files-resolvers-mongodb"
      downloadFile:
        memory: 512
        timeout: 10
      imageTransformer:
        memory: 1600
        timeout: 30
```

Once you change that, don't forget to make a deploy (`webiny deploy-api`).

Let us know if you experience any other issues!

Thanks!
