### ISSUE TITLE
GraphQL security scopes

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#729]
Before moving to Apollo Federation we were able to list all system security scopes via a simple query on `security` field:

```gql
{
    security {
        scopes
    }
}
```

Now that all services are standalone, we no longer have the ability to see all existing scopes. 

## Proposed solution
Each `@webiny/api-*` package that defines GQL schema, should provide a plugin which contains a list of scopes (and possibly a description of each scope?). Then in `serverless.yml` we will use those plugins when deploying the `security` service, like this:

```yaml
security:
  component: "@webiny/serverless-apollo-service"
  inputs:
    region: ${vars.region}
    memory: 512
    timeout: 30
    debug: ${vars.debug}
    plugins:
      - factory: "@webiny/api-plugin-create-apollo-handler"
        options: ${vars.apollo}
      - factory: "@webiny/api-plugin-commodo-db-proxy"
        options:
          functionArn: ${dbProxy.arn}
      - factory: "@webiny/api-security/plugins"
        options: ${vars.security}
      - factory: "@webiny/api-plugin-security-cognito"
        options:
          region: ${vars.region}
          userPoolId: ${cognito.userPool.Id}
      - factory: "@webiny/api-page-builder/plugins/scopes"
      - factory: "@webiny/api-form-builder/plugins/scopes"
      - factory: "@webiny/api-i18n/plugins/scopes"
```

If there are better ways to implement this, I'm open to suggestions.
