### ISSUE TITLE
AWS CodeBuild returns build succeeded when it's failed

### ISSUE THREAD

**Issue by jcode-hub** [webiny/webiny-js#960]
## This is:

- Bug

## Specifications

  - version: cwp-template-full@4.0.2
  - OS: Ubuntu 19.10
  - Browser: Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Expected Behavior
I use AWS CodeBuild to deploy webiny. My deployment role is missing some permissions so the deployment fails with `...is not authorized to perform: iam:GetRole on resource: role ...` however codebuild will end with status succeeded.

## Actual Behavior

The state of the CodeBuild build should be "failed" when the deployment fails.

## Steps to Reproduce the Problem

1. create codebuild project `(Image
aws/codebuild/amazonlinux2-x86_64-standard:3.0 | 
Environment type
Linux | runtime: nodejs10)`
2. use CodeCommit as source provider
3. my buildspec.yml:
```
version: 0.2 
phases: 
  install:
     runtime-versions:
      nodejs: 10
     commands:
      - aws s3 cp "s3://$ENVIRONMENT-webiny-environment-bucket/admin.env.json" apps/admin/.env.json
      - aws s3 cp "s3://$ENVIRONMENT-webiny-environment-bucket/api.env.json" api/.env.json
      - aws s3 cp "s3://$ENVIRONMENT-webiny-environment-bucket/root.env.json" .env.json
      - aws s3 cp "s3://$ENVIRONMENT-webiny-environment-bucket/site.env.json" apps/site/.env.json
      - yarn
  build:
    commands:
      - yarn webiny deploy api --env=$ENVIRONMENT
  post_build:
    commands:
      - aws s3 cp apps/admin/.env.json "s3://$ENVIRONMENT-webiny-environment-bucket/admin.env.json"
      - aws s3 cp api/.env.json "s3://$ENVIRONMENT-webiny-environment-bucket/api.env.json"
      - aws s3 cp apps/site/.env.json "s3://$ENVIRONMENT-webiny-environment-bucket/site.env.json"
      - aws s3 cp .env.json "s3://$ENVIRONMENT-webiny-environment-bucket/root.env.json"
cache:
  paths:
    - ".webiny/**/*"
artifacts:
  type: zip
  files:
    - "**/*"
```
4. make sure your codebuild role is missing some permissions so the deployment will fail
5. start CodeBuild build

## Detailed Description

the codebuild log where it shows the failed deployment. The statusCode says failed but the phase completed successfully:
```

'User: arn:aws:sts::123456789102:assumed-role/codebuild-webiny-deploy-debug-service-role/AWSCodeBuild-9bbd14c0-b930-4a07-beab-ad93eda6ec3c is not authorized to perform: iam:GetRole on resource: role xaa2bha-62ub5ze',
--
293 | code: 'AccessDenied',
294 | time: 2020-06-08T14:11:25.927Z,
295 | requestId: '22032f0d-9822-49fd-8395-2329a7eda65d',
296 | statusCode: 403,
297 | retryable: false,
298 | retryDelay: 90.72291489473072 }
299 |  
300 | Done in 4.63s.
301 |  
302 | [Container] 2020/06/08 14:11:25 Phase complete: BUILD State: SUCCEEDED

```

## Possible Solution

My guess is this has to do with the new `yarn webiny deploy api ...` cmd. I used the same buildspec with the webiny/cli deployment `webiny deploy-api ...` and it worked as expected. Maybe the yarn exit codes are not returned like they should or CodeBuild is not able to read them correctly?
